:root: .
:source: ./src/main/java

= Everything You Never Wanted to Know About Spring Boot 3 AOT

Hi, Spring fans! Spring Boot 3 is here, and it's amazing! If you want to know the broads strokes of what's included, check https://www.youtube.com/watch?v=aUm5WZjh8RA[out this Spring Tips video] for a quick rundown. In this installment, however, I want to look at the details of the brand new ahead-of-time (AOT) compilation engine in Spring Boot 3.

== Introduction

I find it's useful to understand where we were to appreciate where we are now. Traditional Spring applications have _phases_ that they go through when they're run. This isn't exactly what's happening, but here's a simplification of what's happening:


* `ingest` - the Spring application starts up and reads in all the sources of configuration. Remember: Spring Framework is a dependency management framework. It needs to know how your various objects are constructed, their lifecycles (constructors, `InitializingBean#afterPropertiesSet`,`@PostConstruct`, `DisposableBean#destroy`, @PreDestroy), etc. It reads the various configuration files from all the `@Configuration`-annotated classes in your application, through component scanning where Spring discovers classes annotated   with `@Component`. This component scanning also discovers classes annotated with annotations that themselves are annotated with `@Component`, like `@Service`, `@Repository`, @Controller`, and `@RestController`. It also reads in configuration from Spring's classic XML configuration format. (I don't use it, and haven't seen it in the wild in more than half a decade, but still...).
*  `BeanFactory` creation with `BeanDefinition`  instances  - at this point, Spring turns all the various inputs into a metamodel, full of `BeanDefinition` instances. These `BeanDefinition` instances describe the objects that will be wired together. They describe the constructors. The properties to be injected. The setters. The annotations. Everything that will be required to describe this object and get it to a valid state so that it may be given to other objects and just generally start doing work. Importantly, at this phase there are no live-fire beans. Nothing opening ports and sockets. Nothing doing disk IO. None of your business logic will be involved at this point.
* `bean` creation - at this point, Spring will take all the `BeanDefinition`  objects and create from them actual, live-fire beans. Constructors will be called. Lifecycle methods invoked. Dependencies satisfied. At the conclusion of this phase, you'll have an application that's ready to serve production traffic. Which is a nice place to be.


== Enter GraalVm

GraalVM is a dropin replacement for OpenJDK. It _is_ OpenJDK, largely. It has a few extra utilities: notably, a polyglot VM, a native image compiler, and a replacement  HotSpot replacement for the JIT (just-in-time) compiler. We could spend all day on these extra mechanisms, but let's focus on the `native-image` compiler. Henceforth, when I say GraalVM, I'll be referring to the `native-image` compiler.

== You Gotta Start Somewhere...

To start, as always, we'll go to the https://start.spring.io[Spring Initialzr (start.spring.io)]. On 24 November 2022, you'll be able to choose the final Spring Boot 3 general release. But as I write this, I need to use Spring Boot 3 SNAPSHOTS. I'm using Spring Boot 3, Apache Maven, and Java 17. Java 17 is the new baseline for Spring Framework 6 and Spring Boot 3. I'm also using GraalVM 22.3. If you're using the fabulous SDKMAN utility, then you can do the following to get the exact same version of GraalVM that I have on my instance.

[source,shell]
----
sdk install java 22.3.r17-grl
----

I've also added a few dependencies. We won't really touch on these dependencies in any great length, but they'll help us to demonstrate a few concepts, so I've added them.

* Web (`org.springframework.boot` : `spring-boot-starter-web`)
* Actuator (`org.springframework.boot` : `spring-boot-starter-actuator`)
* Spring Data JDBC (`org.springframework.boot` : `spring-boot-starter-data-jdbc`)
* H2 (`com.h2database` : `h2`)

And of course I've got a normal Spring Boot entry class, which looks like this. I won't add anything to this class. I'll be creating new `@Configuration`-annotated classes in subpackages.

[source,java]
----
include::{source}/com/example/aot/AotApplication.java[]
----

Let's look at our first application, a trivial and fairly typical application that - like any other trivial Spring Boot application - works with a database and surfaces an HTTP endpoint. You have seen this before.


[source,java]
-----
include::{source}/com/example/aot/basics/BasicsConfiguration.java[]
-----
<1> look ma, no Lombok!
<2> this is using Spring Data JDBC and you can too!

You'll need some SQL schema, so add `src/main/resources/schema.sql` for our SQL interactions, so let's have Spring Boot create it for us on startup:

[source,sql]
----
include::{root}/src/main/resources/schema.sql[]
----

Run the main class in your IDE or on the command line in the usual ways:

[source,java]
----
mvn -DskipTests spring-boot:run
----

You should see some output on the console. It works. hurray. Moving on, let's turn it into a native image, thusly:

[source,shell]
----
mvn -Pnative -DskipTests native:compile
----

This'll take a minute to finish, so now's a good time to pour a cup of coffee, or tea. Maybe do a crossword puzzle. Reflect on the poor life choices you've made to get to this point where your JVM applications take around a minute. It's a bit dispiriting, isn't it? Always remember: good things come to those who wait!

You'll find the compiled binary in the `target` directory, named `aot`. Run it and you'll see it starts up in no time at all. Like a lightbulb! And, best part, you'll find that it takes very little memory. There are different ways to measure memory, but I find looking at the resident set size to be informative. Here's a script I sue to measure this stuff called `rss.sh`:


[source,shell]
-----
#!/usr/bin/env bash
PID=${1}
RSS=`ps -o rss ${PID} | tail -n1`
RSS=`bc <<< "scale=1; ${RSS}/1024"`
echo "${PID}: ${RSS}M"
-----

It captures the RSS for a given process identifier, scales it to make it easier to parse, then prints it out.  You can find the process identifier for the Spring Boot application in the console, towards the top of the output of the application. Take it and then pass it as the argument for `rss.sh`, thusly:

[source,shell]
-----
./rss.sh <PID>
-----

I tend to get numbers just south of 100MB. Not bad! Don't believe me? How much RAM is your current JVM application taking? I'd be pleasantly surprised if it was a gigabyte or less! Imagine being able to deploy the same application for 1/10th the memory footprint!

== The Spring component model

So, we know the basic stuff's working. But Spring's got a rich, dynamic, multifaceted component model that can do some amazing things. Let's look at some examples, demonstrating a few interesting aspects of the Spring programming model, old and new(-ish) alike.

=== Event Listeners

Did you know that Spring has an event bus that you can use to publish and receive events in one component or another? Any component can fire an event (or more), and any component can listen to, consume, these events. There are two ways to consume events: with a bean of type `ApplicationListener<ApplicationEvent>`, or with the `@EventListener` annotation.

Here's a simple example.

[source,java]
-----
include::{source}/com/example/aot/events/EventsConfiguration.java[]
-----
<1> this is the first more traditional approach: a bean of type `ApplicationListener<T extends ApplicationEvent>`.
<2> this is the newer style, which frees your code of any explicit dependencies on the Spring framework

This example listens for two unrelated events: `WebServerInitializedEvent` tells when the embedded webserver has finished being initialized. The `ApplicationReadyEvent` gets called as late as possible, right before the application handles traffic.

These are just a few of the events that Spring and Spring Boot emit as part of the lifecycle of an application.

=== A Reusable Recipe for Object Creation

Things are never easy. Sometimes objects require finessing and customization. Sometimes, creating an object becomes more complicated than just a simple constructor. It's useful to isolate this construction logic in a single place so that it is reusable. There are at least two patterns that describe this sort  of parameterized construction, besides a constructor:

* the fluid builder pattern
* the factory pattern

There's nothing really to be done to support the first pattern. The second pattern, on the other hand, is well served by the `FactoryBean<T>`. When you register a class of type `FactoryBean<T>` in the Spring context, it is the _product_ (an isntance of type `T`) of that `FactoryBean<T>`, not the `FactoryBean<T>` itself, that is registered in the application context and made available for injection. Let's look at its use in a trivial example:

[source,java]
-----
include::{source}/com/example/aot/factorybeans/FactoryBeansConfiguration.java[]
-----
<1> the `AnimalFactoryBean` produces an object of type `Animal`. But which? Well it depends on the parameters fed into the `FactoryBean`.
<2> the client code injects the `Animal`, ignorant of the construction logic.

=== Scopes

Beans in Spring have a lifecycle that describes the lifetime of a given object. Unless you specify something specifically, the default scope is `singleton`.

* `singleton` - a bean is created when the application starts up and is destroyed when the application shuts down. If a bean has mutable state, then that instance will be visible to all other beans in any other scopes. It's global.
* `session` - a bean is created anew for each new HTTP Session. Each user with an HTTP session will have their own instance of the bean. Changes won't be visible to other clients.
* `web` - each new HTTP request gets a new instance of the bean.
* `thread` - beans are unique to each thread. Sort of like a `ThreadLocal`.

And this mechanism is pluggable, too, so implementors may provide their own scopes, as well. Spring does this across the portfolio, in projects like Spring Web Flow and Spring Batch. You'll also see it in various third party projects like the Spring support for the Flowable workflow engine.

[source,sql]
----
include::{source}/com/example/aot/scopes/ScopesConfiguration.java[]
----
<1> this bean is a `request` scoped, so it'll be created anew for each new incoming HTTP request.
<2> this client-side should be different across different HTTP requests, but the same for successive requests during the same HTTP requests.
<3> We want to make sure that Spring doesn't try to initialize this dependency until we need it, in the middle of an HTTP request. Otherwise, the `request` scope will attempt to resolve the current HTTP request, which won't exist when the application starts up.

Try it out by accessing `http://localhost:8080/scopes/context`.

=== Qualifiers

Qualifiers are conceptually very simple: given two types with the same interface, how does Spring choose which to inject in a given place. The answer is that we _qualify_ the bean we'd like.

Suppose we're trying to build two applications that work with two competing mobile phone marketplace implementations, like the Apple AppStore and Android's Play store.

We might model them with an interface, which we're calling `MobileMarketplace`. In this example, we have two implementations of that interface, and we've used the `@Qualifier` annotation (and a `String` that we provide to distinguish one from the other) on both the bean itself and the place where the bean is injected to. As long as the `String` in the annotation matches, then the right implementation will be injected. This mechanism even goes a bit further:  you can put `@Qualifier` on a custom annotation of your own, and then use that annotation instead of `@Qualifier` directly on the various implementations. This helps you enforce an ubiquitous language. Let's look at an example:

[source,java]
-----
include::{source}/com/example/aot/qualifiers/QualifiersConfiguration.java[]
-----
<1> this bean uses the `android` implementation
<2> this bean uses the `apple` implementation
<3> can't decide? Just inject a `Map<String,T>`, where `T` is the type you're looking for. Spring will provide a map of bean names to bean types.
<4> here we create a meta annotation.
<5> here we create an implementation of the interface


I love that I can define a bean's qualifier using the `@Qualifier` annotation directly, and then inject it into a particular site using the meta annotation. Or, vice versa. Spring doesn't care. It just works.

=== Properties

Spring Framework provides the `Environment` abstraction, which is basically a mapping between a `String` key and a `String` value. How those values are resolved is pluggable, through `PropertyResolver` instances. Spring Boot can then take values in the `Environment` and map them to objects, either via setters or via the constructors of the objects. Here's an example:

[source,java]
-----
include::{source}/com/example/aot/properties/PropertiesConfiguration.java[]
-----
<1> Here, we're injecting a Java object called `DemoProperties`, to which properties starting with `bootiful` are bound
<2> the `@ConfigurationProperties` annotation wires Spring to inject properties on to an instance of `DemoProperties`.

=== See How They Run

You can compile and run all this code in the usual way as a GraalVM native image.

[source,shell]
----
mvn -DskipTests native:compile && ./target/aot
----
