:root: .
:source: ./src/main/java

= Everything You Never Wanted to Know About Spring Boot 3 AOT

Hi, Spring fans! Spring Boot 3 is here, and it's amazing! If you want to know the broads strokes of what's included, check https://www.youtube.com/watch?v=aUm5WZjh8RA[out this Spring Tips video] for a quick rundown. In this installment, however, I want to look at the details of the brand new ahead-of-time (AOT) compilation engine in Spring Boot 3.

== Introduction

I find it's useful to understand where we were to appreciate where we are now. Traditional Spring applications have _phases_ that they go through when they're run. This isn't exactly what's happening, but here's a simplification of what's happening:


* `ingest` - the Spring application starts up and reads in all the sources of configuration. Remember: Spring Framework is a dependency management framework. It needs to know how your various objects are constructed, their lifecycles (constructors, `InitializingBean#afterPropertiesSet`,`@PostConstruct`, `DisposableBean#destroy`, @PreDestroy), etc. It reads the various configuration files from all the `@Configuration`-annotated classes in your application, through component scanning where Spring discovers classes annotated   with `@Component`. This component scanning also discovers classes annotated with annotations that themselves are annotated with `@Component`, like `@Service`, `@Repository`, @Controller`, and `@RestController`. It also reads in configuration from Spring's classic XML configuration format. (I don't use it, and haven't seen it in the wild in more than half a decade, but still...).
*  `BeanFactory` creation with `BeanDefinition`  instances  - at this point, Spring turns all the various inputs into a metamodel, full of `BeanDefinition` instances. These `BeanDefinition` instances describe the objects that will be wired together. They describe the constructors. The properties to be injected. The setters. The annotations. Everything that will be required to describe this object and get it to a valid state so that it may be given to other objects and just generally start doing work. Importantly, at this phase there are no live-fire beans. Nothing opening ports and sockets. Nothing doing disk IO. None of your business logic will be involved at this point.
* `bean` creation - at this point, Spring will take all the `BeanDefinition`  objects and create from them actual, live-fire beans. Constructors will be called. Lifecycle methods invoked. Dependencies satisfied. At the conclusion of this phase, you'll have an application that's ready to serve production traffic. Which is a nice place to be.


== Enter GraalVm

GraalVM is a dropin replacement for OpenJDK. It _is_ OpenJDK, largely. It has a few extra utilities: notably, a polyglot VM, a native image compiler, and a replacement  HotSpot replacement for the JIT (just-in-time) compiler. We could spend all day on these extra mechanisms, but let's focus on the `native-image` compiler. Henceforth, when I say GraalVM, I'll be referring to the `native-image` compiler.

== You Gotta Start Somewhere...

To start, as always, we'll go to the https://start.spring.io[Spring Initialzr (start.spring.io)]. On 24 November 2022, you'll be able to choose the final Spring Boot 3 general release. But as I write this, I need to use Spring Boot 3 SNAPSHOTS. I'm using Spring Boot 3, Apache Maven, and Java 17. Java 17 is the new baseline for Spring Framework 6 and Spring Boot 3. I'm also using GraalVM 22.3. If you're using the fabulous SDKMAN utility, then you can do the following to get the exact same version of GraalVM that I have on my instance.

[source,shell]
----
sdk install java 22.3.r17-grl
----

I've also added a few dependencies. We won't really touch on these dependencies in any great length, but they'll help us to demonstrate a few concepts, so I've added them.

* Web (`org.springframework.boot` : `spring-boot-starter-web`)
* Actuator (`org.springframework.boot` : `spring-boot-starter-actuator`)
* Spring Data JDBC (`org.springframework.boot` : `spring-boot-starter-data-jdbc`)
* H2 (`com.h2database` : `h2`)

And of course I've got a normal Spring Boot entry class, which looks like this. I won't add anything to this class. I'll be creating new `@Configuration`-annotated classes in subpackages.

[source,java]
----
include::{source}/com/example/aot/AotApplication.java[]
----

Let's look at our first application, a trivial and fairly typical application that - like any other trivial Spring Boot application - works with a database and surfaces an HTTP endpoint. You have seen this before.


[source,java]
-----
include::{source}/com/example/aot/basics/BasicsConfiguration.java[]
-----
<1> look ma, no Lombok!
<2> this is using Spring Data JDBC and you can too!

You'll need some SQL schema, so add `src/main/resources/schema.sql` for our SQL interactions, so let's have Spring Boot create it for us on startup:

[source,sql]
----
include::{root}/src/main/resources/schema.sql[]
----

Run the main class in your IDE or on the command line in the usual ways:

[source,java]
----
mvn -DskipTests spring-boot:run
----

You should see some output on the console. It works. hurray. Moving on, let's turn it into a native image, thusly:

[source,shell]
----
mvn -Pnative -DskipTests native:compile
----

This'll take a minute to finish, so now's a good time to pour a cup of coffee, or tea. Maybe do a crossword puzzle. Reflect on the poor life choices you've made to get to this point where your JVM applications take around a minute. It's a bit dispiriting, isn't it? Always remember: good things come to those who wait!

You'll find the compiled binary in the `target` directory, named `aot`. Run it and you'll see it starts up in no time at all. Like a lightbulb! And, best part, you'll find that it takes very little memory. There are different ways to measure memory, but I find looking at the resident set size to be informative. Here's a script I sue to measure this stuff called `rss.sh`:


[source,shell]
-----
#!/usr/bin/env bash
PID=${1}
RSS=`ps -o rss ${PID} | tail -n1`
RSS=`bc <<< "scale=1; ${RSS}/1024"`
echo "${PID}: ${RSS}M"
-----

It captures the RSS for a given process identifier, scales it to make it easier to parse, then prints it out.  You can find the process identifier for the Spring Boot application in the console, towards the top of the output of the application. Take it and then pass it as the argument for `rss.sh`, thusly:

[source,shell]
-----
./rss.sh <PID>
-----

I tend to get numbers just south of 100MB. Not bad! Don't believe me? How much RAM is your current JVM application taking? I'd be pleasantly surprised if it was a gigabyte or less! Imagine being able to deploy the same application for 1/10th the memory footprint!

== The Spring component model

So, we know the basic stuff's working. But Spring's got a rich, dynamic, multifaceted component model that can do some amazing things. Let's look at some examples, demonstrating a few interesting aspects of the Spring programming model, old and new(-ish) alike.

=== Event Listeners

Did you know that Spring has an event bus that you can use to publish and receive events in one component or another? Any component can fire an event (or more), and any component can listen to, consume, these events. There are two ways to consume events: with a bean of type `ApplicationListener<ApplicationEvent>`, or with the `@EventListener` annotation.

Here's a simple example.

[source,java]
-----
include::{source}/com/example/aot/events/EventsConfiguration.java[]
-----
<1> this is the first more traditional approach: a bean of type `ApplicationListener<T extends ApplicationEvent>`.
<2> this is the newer style, which frees your code of any explicit dependencies on the Spring framework

This example listens for two unrelated events: `WebServerInitializedEvent` tells when the embedded webserver has finished being initialized. The `ApplicationReadyEvent` gets called as late as possible, right before the application handles traffic.

These are just a few of the events that Spring and Spring Boot emit as part of the lifecycle of an application.

=== A Reusable Recipe for Object Creation

Things are never easy. Sometimes objects require finessing and customization. Sometimes, creating an object becomes more complicated than just a simple constructor. It's useful to isolate this construction logic in a single place so that it is reusable. There are at least two patterns that describe this sort  of parameterized construction, besides a constructor:

* the fluid builder pattern
* the factory pattern

There's nothing really to be done to support the first pattern. The second pattern, on the other hand, is well served by the `FactoryBean<T>`. When you register a class of type `FactoryBean<T>` in the Spring context, it is the _product_ (an isntance of type `T`) of that `FactoryBean<T>`, not the `FactoryBean<T>` itself, that is registered in the application context and made available for injection. Let's look at its use in a trivial example:

[source,java]
-----
include::{source}/com/example/aot/factorybeans/FactoryBeansConfiguration.java[]
-----
<1> the `AnimalFactoryBean` produces an object of type `Animal`. But which? Well it depends on the parameters fed into the `FactoryBean`.
<2> the client code injects the `Animal`, ignorant of the construction logic.

=== Scopes

Beans in Spring have a lifecycle that describes the lifetime of a given object. Unless you specify something specifically, the default scope is `singleton`.

* `singleton` - a bean is created when the application starts up and is destroyed when the application shuts down. If a bean has mutable state, then that instance will be visible to all other beans in any other scopes. It's global.
* `session` - a bean is created anew for each new HTTP Session. Each user with an HTTP session will have their own instance of the bean. Changes won't be visible to other clients.
* `web` - each new HTTP request gets a new instance of the bean.
* `thread` - beans are unique to each thread. Sort of like a `ThreadLocal`.

And this mechanism is pluggable, too, so implementors may provide their own scopes, as well. Spring does this across the portfolio, in projects like Spring Web Flow and Spring Batch. You'll also see it in various third party projects like the Spring support for the Flowable workflow engine.

[source,sql]
----
include::{source}/com/example/aot/scopes/ScopesConfiguration.java[]
----
<1> this bean is a `request` scoped, so it'll be created anew for each new incoming HTTP request.
<2> this request-scoped bean should be different across different HTTP requests, but the same for successive accesses during the same HTTP request.
<3> Spring is giving us a proxy, which won't be initialized with real values until the bean starts its lifecycle, bound to whatever externalities govern them.

Try it out by accessing `http://localhost:8080/scopes/context`.

=== Qualifiers

Qualifiers are conceptually very simple: given two types with the same interface, how does Spring choose which to inject in a given place. The answer is that we _qualify_ the bean we'd like.

Suppose we're trying to build two applications that work with two competing mobile phone marketplace implementations, like the Apple AppStore and Android's Play store.

We might model them with an interface, which we're calling `MobileMarketplace`. In this example, we have two implementations of that interface, and we've used the `@Qualifier` annotation (and a `String` that we provide to distinguish one from the other) on both the bean itself and the place where the bean is injected to. As long as the `String` in the annotation matches, then the right implementation will be injected. This mechanism even goes a bit further:  you can put `@Qualifier` on a custom annotation of your own, and then use that annotation instead of `@Qualifier` directly on the various implementations. This helps you enforce an ubiquitous language. Let's look at an example:

[source,java]
-----
include::{source}/com/example/aot/qualifiers/QualifiersConfiguration.java[]
-----
<1> this bean uses the `android` implementation
<2> this bean uses the `apple` implementation
<3> can't decide? Just inject a `Map<String,T>`, where `T` is the type you're looking for. Spring will provide a map of bean names to bean types.
<4> here we create a meta annotation.
<5> here we create an implementation of the interface


I love that I can define a bean's qualifier using the `@Qualifier` annotation directly, and then inject it into a particular site using the meta annotation. Or, vice versa. Spring doesn't care. It just works.

=== Properties

Spring Framework provides the `Environment` abstraction, which is basically a mapping between a `String` key and a `String` value. How those values are resolved is pluggable, through `PropertyResolver` instances. Spring Boot can then take values in the `Environment` and map them to objects, either via setters or via the constructors of the objects. Here's an example:

[source,java]
-----
include::{source}/com/example/aot/properties/PropertiesConfiguration.java[]
-----
<1> Here, we're injecting a Java object called `DemoProperties`, to which properties starting with `bootiful` are bound
<2> the `@ConfigurationProperties` annotation wires Spring to inject properties on to an instance of `DemoProperties`.

=== See How They Run

You can compile and run all this code in the usual way as a GraalVM native image.

[source,shell]
----
mvn -DskipTests native:compile && ./target/aot
----

Run the application and you should see all the output from the previous examples, as expected. The best part? It'll have started in no time at all, and be a far sight smaller as a binary and as a process occupying RAM. You can use the script we introduced above to measure the process' Resident Set Size (RSS).

== Detecting that you're in a Native Image

Sometimes, hopefully not often, but sometimes you'll want to know whether your code is running in a native image context. This is useful because, as good as Spring's AOT engine is, we can't make it work perfectly in every situation, short of reviewing every line of code ever written. There are oddities that arise from working in a GraalVM native image, and it's important to be aware of those.


There is, mercifully, one useful System property that you can use here: `org.graalvm.nativeimage.imagecode`.  We've encapsulated that check in `NativeDetector.inNativeImage()`. Here it is in action.

[source,java]
----
include::{source}/com/example/aot/detection/DetectionConfiguration.java[]
----

Run it on the JRE and it'll return `false`. Run it in a GraalVM native image, and it'll return `true`.

My first instinct when I learned about that property was to wrap it in a `Condition` object, and then use `@Conditional` to call that `Condition`, and thus make beans available in the Spring `BeanFactory` _conditionally_. I tried it, and it didn't work. Here's why.

Recall our discussion around the _phases_ of a Spring Boot application. It starts up, _ingests_ all the configuration, then creates a meta model representation of the beans (`BeanDefinition`s). Then, finally, it creates all those beans out of those `BeanDefinition`s.

In an AOT application intended for GraalVM native image compilation, Spring creates a `BeanFactory` with `BeanDefinition` and then stops there. It lets code inspect the various beans in the `BeanFactory` and then that code writes out an optimized version of the `BeanFactory`, skipping all the ingest and going straight to the live beans, for use in the GraalVM native image context. An important part of this is that it does this _only for the beans that are present in the `BeanFactory` during compilation.

There are two things that can dynamically change the beans in a given `BeanFactory`: conditionals, and profiles. I'd strongly urge you to avoid using profiles, and a handful of conditionals, if you intend to go to a GraalVM native image.

Profiles only work if you activate the profile during compilation. The profiles must be evaluated at compile time. Otherwise, beans not in an active profile won won't be present in the native image heap and thus can't be activated at runtime.

Conditions are evaluated at compile time. The conditions that are invariant at compilation time and runtime - like `@ConditionalOnClass` and `@ConditionalOnProperty` - work just fine in the native world: the classes present at compile time are by definition the classes present at runtime. Some conditions depend on ambient state, however, like whether you're running in a Kubernetes cluster (`@ConditionalOnCloudPlatform(Kubernetes)`). Avoid these, unless you plan on compiling your code in a Kubernetes cluster.



== Processing the Bean Factory

We've talked about the `BeanFactory`. It's basically a container, an aggregation, of all the beans in your application. In earlier sections we saw that the beans in the `BeanFactory` are created as `BeanDefinition` instances. These `BeanDefinition`s are the metamodel representation of your object graph. They describe all the dependencies, constructors, annotations, fields, etc., related to your bean instances.

Spring makes it trivial to act on those collection of `BeanDefinition` instances through callback interfaces that are evaluated at compile time (AOT) and runtime (JRE). The `BeanFactoryPostProcessor` is a callback interface that lets us have access to the `BeanFactory` and to manipulate the `BeanDefinition` instances. We can regiser new ones, update existing ones, or even remove them in this interface and in other, more specific subclasses of this interface. The `BeanFactory` is not fixed at this point. Various Spring projects use this fact to great effect. Before we turned the Spring Cloud project into an umbrealla project that included a ton of different libraries to make working with microservices easier, its sole function was to make it easy for Spring Boot appliations deployed to a Platform-as-a-Service (PaaS) like Cloud Foundry or Heroku to connect to managed infrastructure like a database or a message queue. It did this by analuzing the `BeanFactory`, identifying infrastructure-related beans like `javax.sql.DataSource`, and then replacing them with a new bean of an identical interface, but with a connection pointing to the managed infrastructure identified by environment variables in the process space of the running application. So, you write an application using a `DataSource` talking to an embedded H2 instance on your loccal machine, but when you deploy it, this `BeanFactoryPostProcessor` identifies connection strings in environment variables in the process space for the application and uses that to create a proper `DataSource` talking to that managed infrastructure, presumably on another host and port. And this was all transprent to the user, which is what we want.

The `BeanFactoryPostProcessor` is a great place to see _everything_ in the `BeanFactory` all in one place when the application starts up.

the `BeanFactoryInitializationAotProcessor` is a new itnerface that is sort of a peer t the `BeanFactoryPostProcessor`. It runs at compile time, and you have basically the same contract: you can choose to contribute hints (or even do code-generation) whuile analyzing the `BeanDefinition`s in the application.

It's important that you work only in terms of the `BeanDefinition` instances and bean names, in botht hese interfaces. Remember, at this point Spring hasn't created any of theb eans. So, while you'll be able to call `BeanFactory#getBean(String)`, it'll force  Spring to eagerly initialize the object, calling the constructor and the methods and so on before the bean is ready. Don't do this - it'll really screw things up!


Let's look a trivial example. We'll write a `BeanFactoryPostProcessor` that analyzes programmatically registers a new `BeanDefinition` in the application context. Would you ever nee dto do this? No. but it's hopefully illustrative. We'll use a subclass of `BeanFactoryPostProcessor` called `BeanDefinitionRegistryPostProcessor`, which gives us a `BeanFactory` downcast to a specific subtype that supports programatically registering new beans. The trouble is that this bean we'll register is going to require some reflection usign the Jackson JSON API, so well need to also register a GraalVM hint for it using a `BeanFactoryInitializationAotProcessor` contribution.


[source,java]
----
include::{source}/com/example/aot/bfpp/BfppConfiguration.java[]
----
<1> were going to work with the same bean both at compile time and at runtime. So, I've stashed a variable with the name of the bean here for access from both interfaces at both phases
<2> Note that the bean definitions here are registered with the `static` keyword. Spring will involve these beans very early in the lifecycle of the application context. It won't have any livefire beans except for these very early beans. So, we use `static` to avoid depending on anything from the `BeanFactory`. And don't force Spring to construct the `@Configuration` class containing the `@Bean` registration methods, too.
<3> the `Listener` is a trivla `ApplicationListener` that, wehn run, will iterate over a collection of dummy DTOs and print them out using Jackson for JSON serialization. This serialization involves reflection, for wihch we'll need to furnish hints.
<4> the first callback, the `ListenerBeanFactoryPostProcessor`, programatically registers a new `BeanDefinition` of type `Listener` if a bean of the name we've specified in the variable doesn't already exist in the context. This object runs at runtime, in both the JRE and the AOT application. Here were changing, molding, the `BeanFactory`.
<5> when we compile the application using the AOT engine, intending to biold a graalvm native image, Spring Boot will aso run the the `ListenerBeeanFactoryInitializationAotProcessor`, which - knoiwing that we'll eventually register a `Listener` bean - furnishes the requisite hints to make the JSON serialization of the `Product` records work.

These two itnerfaces work well together. They complement each other.